// We keep all project details here in an array of objects.
// This allows our Projects page to simply "map" through the list to generate cards,
// instead of hard-coding the layout for every single project!

export const PROJECTS = [
  {
    id: "heart-iq",
    title: "Heart-IQ — Cardiac Prediction",
    subtitle: "Scikit-Learn Prediction Web App",
    year: "2026",
    desc: "Built an end-to-end cardiac risk prediction web app that analyzes patient clinical profiles and outputs heart disease probability scores using a pre-trained Scikit-learn ML model. Features SMTP OTP recovery and interactive Plotly visualizations.",
    tags: ["Python", "Streamlit", "Scikit-Learn", "Plotly", "ML"], // Used for the pills
    live: "https://heartiqai.vercel.app/", // Used for the "Live Demo" button
    github: "https://github.com/Umangpandey75/-Heart-IQ-Cardiac-Prediction-System", // Used for the "Code" button
    color: "#6B48FF", // The theme color for this specific card
    featured: true, // If true, it gets a "⭐ Featured" badge and appears in the "Featured" tab
    img: "/project_fakebuster.png",
  },
  {
    id: "mindmapr-ai",
    title: "MindMapr-AI",
    subtitle: "AI-Powered Text-to-Mindmap",
    year: "2026",
    desc: "A Python-powered utility that leverages generative AI models to convert textual brainstorming, notes, and documentation into structured, hierarchical visual mind maps for study and reference.",
    tags: ["Python", "Generative AI", "Data Structures", "NLP"],
    live: "https://mindmetric001.vercel.app/",
    github: "https://github.com/Umangpandey75/MindMapr-AI",
    color: "#6B48FF",
    featured: true,
    img: "/project_mindmetric.png",
  },
  {
    id: "email-sarthi",
    title: "EmailSarthi",
    subtitle: "Automated Email Broadcasting",
    year: "2026",
    desc: "A lightweight email automation and broadcasting platform that lets users send batch emails and templates with custom validations, reliable tracking, structured input forms, and automated logs.",
    tags: ["HTML5", "CSS3", "JavaScript", "Email API", "Automation"],
    live: "https://emailsarthi.vercel.app/",
    github: "https://github.com/Umangpandey75/EmailSarthi",
    color: "#E8A045",
    featured: true,
    img: "/project_emailsarthi.png",
  },
  {
    id: "genderify-ai",
    title: "Genderify-AI",
    subtitle: "AI Image & Video Classifier",
    year: "2026",
    desc: "A full-stack image and video classification application designed to detect gender (male or female) in real-time. Features a high-accuracy, fine-tuned deep learning model served via a Python Flask API backend and an elegant, responsive React frontend.",
    tags: ["Python", "TensorFlow", "Flask", "React", "CNN"],
    live: "https://genderifyai.vercel.app/",
    github: "https://github.com/Umangpandey75/Genderify-AI-",
    color: "#00CEA8",
    featured: false,
    img: "/project_genderify.png",
  },
  {
    id: "voice-to-story",
    title: "Voice to Story Generator",
    subtitle: "AI Creative Writing Studio",
    year: "2026",
    desc: "An AI-powered creative writing studio that transforms spoken conversations, voice recordings, and dialogue audio files into rich, stylized narrative stories. Built on the MERN stack with the official Google Gemini SDK.",
    tags: ["Gemini SDK", "MERN Stack", "React", "Node.js", "Voice AI"],
    live: "https://voicetostory.vercel.app/",
    github: "https://github.com/Umangpandey75/Voice-to-Story-Generator",
    color: "#E8A045",
    featured: false,
    img: "/project_voice_story.png",
  },
  {
    id: "hr-analytics-dashboard",
    title: "HR Analytics Dashboard",
    subtitle: "Power BI Attrition Dashboard",
    year: "2025",
    desc: "An interactive Power BI report designed to analyze employee attrition, workforce demographics, salary distribution, and employee retention trends. Integrates CSV dataset, models complex DAX KPIs, and delivers data-driven insights.",
    tags: ["Power BI", "DAX", "Excel", "Data Analytics"],
    live: "https://app.fabric.microsoft.com/groups/me/reports/06041f81-db2c-4ef0-a0b6-d6e97363aa51/1901196bc7c6d04666c9?ctid=8869cc11-7d78-4a5c-8378-b78ce12cb498&experience=power-bi",
    github: "https://github.com/Umangpandey75/HR-Analytics-Dashboard",
    color: "#6B48FF",
    featured: false,
    img: "/project_hr_dashboard.png",
  },
  {
    id: "performance-dashboard",
    title: "Employee Performance Dashboard",
    subtitle: "Power BI Analytics Dashboard",
    year: "2025",
    desc: "Engineered an interactive Power BI dashboard by integrating data from multiple sources (Excel, SQL Server, CSV), reducing manual reporting time by 10%. Designed complex DAX measures and calculated columns to derive KPIs like performance scores, attendance rates, and departmental comparisons. Implemented dynamic row-level security (RLS) to manage data visibility.",
    tags: ["Power BI", "SQL Server", "Excel", "DAX", "Data Viz"],
    live: "#",
    github: "https://github.com/Umangpandey75",
    color: "#E8A045",
    featured: false,
    img: "/project_gitglow.png",
  },
  {
    id: "resume-builder",
    title: "Resume Builder",
    subtitle: "Dynamic CV Structuring App",
    year: "2026",
    desc: "A responsive client-side web application designed to help job-seekers build, preview, and format resume templates dynamically using structured input forms and print-ready CSS styles.",
    tags: ["HTML5", "CSS3", "JavaScript", "Branding"],
    live: "#",
    github: "https://github.com/Umangpandey75/Resume-Builder",
    color: "#00CEA8",
    featured: false,
    img: "/project_portfolio3d.png",
  },
  {
    id: "ipl-fantasy",
    title: "IPL Fantasy",
    subtitle: "Modern Fantasy Cricket Platform",
    year: "2026",
    desc: "A premium, modern fantasy cricket platform that lets you build your dream XI from 10 IPL teams within a 100-credit budget. Choose your Captain & Vice-Captain, save your team to the global leaderboard, compete in contests, and analyze real IPL player stats.",
    tags: ["React", "Next.js", "Sports Analytics"],
    live: "https://iplfantasy.space-z.ai/",
    github: "https://github.com/Umangpandey75/IPL_Fantasy",
    color: "#6B48FF",
    featured: false,
    img: "/project_ipl_fantasy.png",
  },
  {
    id: "umangverse-youtube",
    title: "UmangVerse",
    subtitle: "Full-Stack Video-Sharing Platform",
    year: "2026",
    desc: "A modern, full-stack video-sharing platform built to replicate the core experience of YouTube. It features a custom-built video player, dynamic content discovery, and a highly interactive user interface.",
    tags: ["Next.js", "React", "Video Streaming"],
    live: "https://umangverse.space-z.ai/",
    github: "https://github.com/Umangpandey75/UmangVerse__Youtube",
    color: "#E8A045",
    featured: false,
    img: "/project_umangverse.png",
  },
  {
    id: "costvision-ai",
    title: "CostVision AI",
    subtitle: "AI Tool Spending Audit Platform",
    year: "2026",
    desc: "An intelligent, free audit platform designed to help startups analyze and optimize their AI tool spending on subscriptions like ChatGPT, Claude, Copilot, and Cursor.",
    tags: ["AI", "SaaS", "Data Audit"],
    live: "https://costvisionai.vercel.app",
    github: "https://github.com/Umangpandey75/CostVision_AI",
    color: "#00CEA8",
    featured: false,
    img: "/project_costvision.png",
  },
  {
    id: "spenza-expense",
    title: "Spenza",
    subtitle: "Expense Management System",
    year: "2026",
    desc: "A fast, transparent, and delightful expense management application for friends, roommates, and travel groups. Removes the friction of splitting bills using modern web technologies.",
    tags: ["Next.js 15", "Finance", "Expense Tracker"],
    live: "https://spendinspenza.vercel.app/",
    github: "https://github.com/Umangpandey75/Spenza-_-roommate-tour_Spliting_management_system",
    color: "#6B48FF",
    featured: false,
    img: "/project_spenza.png",
  },
  {
    id: "ipl-pulse",
    title: "IPL Pulse Dashboard",
    subtitle: "Comprehensive Cricket Dashboard",
    year: "2026",
    desc: "A visually stunning dashboard built for cricket enthusiasts. It archives every match, team, and player statistic from the Indian Premier League (2008 to 2026) using React and Next.js.",
    tags: ["React", "Data Visualization", "Dashboard"],
    live: "#",
    github: "https://github.com/Umangpandey75/IPL-Pulse-Dashboard-",
    color: "#E8A045",
    featured: false,
    img: "/project_ipl_pulse.png",
  },
];

export type Project = (typeof PROJECTS)[0];
