// We keep all project details here in an array of objects.
// This allows our Projects page to simply "map" through the list to generate cards,
// instead of hard-coding the layout for every single project!

export const PROJECTS = [
  {
    id: "heart-iq",
    title: "Heart-IQ — Cardiac Prediction",
    subtitle: "Scikit-Learn Prediction Web App",
    year: "2026",
    desc: "Built an end-to-end cardiac risk prediction web app that analyzes patient clinical profiles and outputs heart disease probability scores using a pre-trained Scikit-learn ML model. Features SMTP OTP recovery and interactive Plotly visualizations.",
    tags: ["Python", "Streamlit", "Scikit-Learn", "Plotly", "ML"], // Used for the pills
    live: "https://heartiqai.vercel.app/", // Used for the "Live Demo" button
    github: "https://github.com/Umangpandey75/-Heart-IQ-Cardiac-Prediction-System", // Used for the "Code" button
    color: "#6B48FF", // The theme color for this specific card
    featured: true, // If true, it gets a "⭐ Featured" badge and appears in the "Featured" tab
    img: "/project_fakebuster.png",
  },
  {
    id: "mindmapr-ai",
    title: "MindMapr-AI",
    subtitle: "AI-Powered Text-to-Mindmap",
    year: "2026",
    desc: "A Python-powered utility that leverages generative AI models to convert textual brainstorming, notes, and documentation into structured, hierarchical visual mind maps for study and reference.",
    tags: ["Python", "Generative AI", "Data Structures", "NLP"],
    live: "https://mindmetric001.vercel.app/",
    github: "https://github.com/Umangpandey75/MindMapr-AI",
    color: "#6B48FF",
    featured: true,
    img: "/project_mindmetric.png",
  },
  {
    id: "email-sarthi",
    title: "EmailSarthi",
    subtitle: "Automated Email Broadcasting",
    year: "2026",
    desc: "A lightweight email automation and broadcasting platform that lets users send batch emails and templates with custom validations, reliable tracking, structured input forms, and automated logs.",
    tags: ["HTML5", "CSS3", "JavaScript", "Email API", "Automation"],
    live: "https://emailsarthi.vercel.app/",
    github: "https://github.com/Umangpandey75/EmailSarthi",
    color: "#E8A045",
    featured: true,
    img: "/project_emailsarthi.png",
  },
  {
    id: "genderify-ai",
    title: "Genderify-AI",
    subtitle: "AI Image & Video Classifier",
    year: "2026",
    desc: "A full-stack image and video classification application designed to detect gender (male or female) in real-time. Features a high-accuracy, fine-tuned deep learning model served via a Python Flask API backend and an elegant, responsive React frontend.",
    tags: ["Python", "TensorFlow", "Flask", "React", "CNN"],
    live: "https://genderifyai.vercel.app/",
    github: "https://github.com/Umangpandey75/Genderify-AI-",
    color: "#00CEA8",
    featured: false,
    img: "/project_genderify.png",
  },
  {
    id: "voice-to-story",
    title: "Voice to Story Generator",
    subtitle: "AI Creative Writing Studio",
    year: "2026",
    desc: "An AI-powered creative writing studio that transforms spoken conversations, voice recordings, and dialogue audio files into rich, stylized narrative stories. Built on the MERN stack with the official Google Gemini SDK.",
    tags: ["Gemini SDK", "MERN Stack", "React", "Node.js", "Voice AI"],
    live: "https://voicetostory.vercel.app/",
    github: "https://github.com/Umangpandey75/Voice-to-Story-Generator",
    color: "#E8A045",
    featured: false,
    img: "/project_voice_story.png",
  },
  {
    id: "hr-analytics-dashboard",
    title: "HR Analytics Dashboard",
    subtitle: "Power BI Attrition Dashboard",
    year: "2025",
    desc: "An interactive Power BI report designed to analyze employee attrition, workforce demographics, salary distribution, and employee retention trends. Integrates CSV dataset, models complex DAX KPIs, and delivers data-driven insights.",
    tags: ["Power BI", "DAX", "Excel", "Data Analytics"],
    live: "https://app.fabric.microsoft.com/groups/me/reports/06041f81-db2c-4ef0-a0b6-d6e97363aa51/1901196bc7c6d04666c9?ctid=8869cc11-7d78-4a5c-8378-b78ce12cb498&experience=power-bi",
    github: "https://github.com/Umangpandey75/HR-Analytics-Dashboard",
    color: "#6B48FF",
    featured: false,
    img: "/project_hr_dashboard.png",
  },
  {
    id: "performance-dashboard",
    title: "Employee Performance Dashboard",
    subtitle: "Power BI Analytics Dashboard",
    year: "2025",
    desc: "Engineered an interactive Power BI dashboard by integrating data from multiple sources (Excel, SQL Server, CSV), reducing manual reporting time by 10%. Designed complex DAX measures and calculated columns to derive KPIs like performance scores, attendance rates, and departmental comparisons. Implemented dynamic row-level security (RLS) to manage data visibility.",
    tags: ["Power BI", "SQL Server", "Excel", "DAX", "Data Viz"],
    live: "#",
    github: "https://github.com/Umangpandey75",
    color: "#E8A045",
    featured: false,
    img: "/project_gitglow.png",
  },
  {
    id: "speech-trans",
    title: "SpeechTrans — AI Translation",
    subtitle: "AI Audio/Video Hindi Dubber",
    year: "2026",
    desc: "An AI-based speech translation system that automatically converts English audio/video into natural, synchronized Hindi speech. Developed for automated dubbing, translation accessibility, and cross-language communication using voice analysis.",
    tags: ["Python", "AI Dubbing", "Jupyter", "Acoustics"],
    live: "#",
    github: "https://github.com/Umangpandey75/SpeechTrans",
    color: "#00CEA8",
    featured: false,
    img: "/project_yogaflow.png",
  },
  {
    id: "resume-builder",
    title: "Resume Builder",
    subtitle: "Dynamic CV Structuring App",
    year: "2026",
    desc: "A responsive client-side web application designed to help job-seekers build, preview, and format resume templates dynamically using structured input forms and print-ready CSS styles.",
    tags: ["HTML5", "CSS3", "JavaScript", "Branding"],
    live: "#",
    github: "https://github.com/Umangpandey75/Resume-Builder",
    color: "#00CEA8",
    featured: false,
    img: "/project_portfolio3d.png",
  },
  {
    id: "vocal-ai",
    title: "Vocal-AI",
    subtitle: "Speech Recognition & Speech-to-Text",
    year: "2026",
    desc: "A voice analysis and processing application built in Python that detects acoustic features, records user speech, and performs speech-to-text with semantic keyword highlights.",
    tags: ["Python", "Voice Analytics", "NLP", "Speech-to-Text"],
    live: "#",
    github: "https://github.com/Umangpandey75/Vocal-AI",
    color: "#E8A045",
    featured: false,
    img: "/project_vocalai.png",
  },
];

export type Project = (typeof PROJECTS)[0];
